### ISSUE TITLE
Agent source code

### ISSUE THREAD

**Issue by 89z** [ngrok/choco-ngrok#1]
Where is the source code for the agent?

https://github.com/ngrok/choco-ngrok/blob/59fbf01ac957e448a096ba44bfa1eb049bef37c1/tools/chocolateyinstall.ps1#L6-L7

**Comment by 89z** [comment]
Hm, look like close source:

https://github.com/inconshreveable/ngrok#ngrok-2x

**Comment by euank** [comment]
Indeed, the ngrok agent's source code isn't available for the v2 or v3 agent. Sorry :(
