### ISSUE TITLE
ngrok config check fails

### ISSUE THREAD

**Issue by davidmwhynot** [ngrok/choco-ngrok#13]
After running `choco install ngrok` in the following context:

- Windows 11
- Git bash in windows terminal (running w/ admin privs)

I experience this issue:
```
$ ngrok config check
bash: /c/Users/david/ngrok: No such file or directory
$ ngrok --version
bash: /c/Users/david/ngrok: No such file or directory
$ ngrok --help
bash: /c/Users/david/ngrok: No such file or directory
```

Running `touch ~/ngrok` fixed the issue.

**Comment by bobzilladev** [comment]
Hello, thanks for writing in! That is an odd behavior which I am trying to duplicate. Could you give us the output from some of those commands now that it is working?

1. `which ngrok`
1. `ngrok config check`
1. `ngrok --version`

For comparison, this is what I'm seeing in an admin-priv git bash shell (MINGW64):
```
$ choco install ngrok -y --force
...
Download of ngrok-v3-3.5.0-windows-amd64.zip (8.69 MB) completed.
 The install of ngrok was successful.
 Software installed to 'C:\ProgramData\chocolatey\lib\ngrok\tools'
...
$ which ngrok
/c/ProgramData/chocolatey/bin/ngrok
$ ngrok config check
Valid configuration file at C:\Users\b-tea\.ngrok2\ngrok.yml
$ ngrok --version
ngrok version 3.5.0
```
Thank you for the feedback!

**Comment by bobzilladev** [comment]
Hello, just wanted to check in and see if there were any more updates you could provide on debugging this issue, since we were not able to duplicate it. Glad you got it working in the meantime!

**Comment by bobzilladev** [comment]
Will close out this ticket, feel free to reopen if the issue reoccurs or there is any additional information or questions. Thanks for writing in!
